import { getDatabasePool } from '../database/index.js';
import config from '../config/index.js';
import logger from '../utils/logger.js';

/**
 * Calculates the Hamming distance between two 16-character hex strings.
 * Represents the number of differing bits.
 */
export function getHammingDistance(hash1, hash2) {
  if (hash1 === hash2) return 0;
  
  try {
    const b1 = BigInt(`0x${hash1}`);
    const b2 = BigInt(`0x${hash2}`);
    
    let xor = b1 ^ b2;
    let distance = 0;
    
    // Brian Kernighan's algorithm to count set bits
    while (xor > 0n) {
      xor &= xor - 1n;
      distance++;
    }
    
    return distance;
  } catch (err) {
    // If parsing fails, fall back to string-level approximation or infinity
    return Infinity;
  }
}

/**
 * Checks the database to see if this pHash has a perceptual duplicate.
 *
 * @param {string} candidatePhash - The 16-character hex hash.
 * @returns {Promise<Object>} - Duplicate lookup result.
 */
export async function checkPhashDuplicate(candidatePhash) {
  if (!candidatePhash || typeof candidatePhash !== 'string' || candidatePhash.length !== 16) {
    throw new Error('Valid 16-character candidatePhash is required');
  }

  const db = getDatabasePool();
  if (!db) {
    logger.warn('phashDuplicateDetector: Database disabled, assuming candidate is unique');
    return {
      duplicate: false,
      reason: 'database_unavailable',
      distance: null,
      threshold: config.PHASH_DISTANCE_THRESHOLD,
      matched_candidate_id: null
    };
  }

  try {
    // Fetch stored hashes for accepted/queued candidates.
    // For large scale, Postgres extensions like pg-similarity or specific Hamming indexes are used.
    // Here we load a bounded window of recent accepted hashes to do in-memory comparison.
    // This queries true DCT pHash values generated by the current system.
    const res = await db.query(`
      SELECT id, phash FROM discovery_candidates 
      WHERE phash IS NOT NULL 
      AND status IN ('queued', 'processing', 'ingested', 'embedded', 'success')
      ORDER BY updated_at DESC
      LIMIT 10000
    `);

    let bestDistance = Infinity;
    let bestMatchId = null;

    for (const row of res.rows) {
      if (!row.phash || row.phash.length !== 16) continue;

      const dist = getHammingDistance(candidatePhash, row.phash);
      
      if (dist < bestDistance) {
        bestDistance = dist;
        bestMatchId = row.id;
      }

      // Early exit if exact match
      if (bestDistance === 0) break;
    }

    const threshold = config.PHASH_DISTANCE_THRESHOLD;

    if (bestDistance <= threshold) {
      return {
        duplicate: true,
        reason: 'phash_perceptual_match',
        distance: bestDistance,
        threshold: threshold,
        matched_candidate_id: bestMatchId
      };
    }

    return {
      duplicate: false,
      reason: 'phash_no_match',
      distance: bestDistance === Infinity ? null : bestDistance,
      threshold: threshold,
      matched_candidate_id: null
    };

  } catch (err) {
    logger.error('Failed to query perceptual duplicate', { error: err.message, phash: candidatePhash });
    return {
      duplicate: false,
      reason: 'database_error',
      distance: null,
      threshold: config.PHASH_DISTANCE_THRESHOLD,
      matched_candidate_id: null
    };
  }
}
